import { defineStyleConfig } from "@chakra-ui/styled-system";

export const EDXErrorPageTheme = {
  base: {
    bgColor: { value: '{colors.gray.50.value}' },
    display: { value: 'flex' },
    flexDirection: { value: 'column' },
    justifyContent: { value: 'center' },
    alignItems: { value: 'center' },
    width: { value: '100vw' },
    minWidth: { value: '100vw' },
    height: { value: '100vh' },
    minHeight: { value: '100vh' },
    contentContainer: {
      flexDirection: { value: 'column' },
      maxWidth: { value: '37.5rem' },
      gap: { value: '1rem' },
      padding: { value: '1rem 0' },
    },
    errorCodeContainer: {
      color: { value: '{colors.black.value}' },
      textAlign: { value: 'center' },
      fontFamily: { value: 'Poppins' },
      fontSize: { value: '1.5rem' },
      fontWeight: { value: '600' },
      textTransform: { value: 'uppercase' },
    },
    errorTitleContainer: {
      color: { value: '{colors.black.value}' },
      textAlign: { value: 'center' },
      fontFamily: { value: 'Poppins' },
      fontSize: { value: '2rem' },
      fontWeight: { value: '700' },
    },
    errorDescription: {
      padding: { value: '0 1rem' },
      color: { value: '{colors.black.value}' },
      textAlign: { value: 'center' },
      fontFamily: { value: 'Poppins' },
      fontSize: { value: '1rem' },
      fontWeight: { value: '400' },
    },
    buttonsContainer: {
      gap: { value: '1rem' },
      alignItems: { value: 'center' },
      justifyContent: { value: 'center' },
      marginTop: { value: '1rem' },
    },
    primaryButton: {
      fontSize: { value: '0.75rem' },
      fontWeight: { value: '600' },
      lineHeight: { value: '1.5rem' },
      textTransform: { value: 'uppercase' },
      height: { value: '2rem' },
      borderRadius: { value: '0.25rem' },
      padding: { value: '0 0.5rem' },
    },
    secondaryButton: {
      fontSize: { value: '0.75rem' },
      fontWeight: { value: '600' },
      lineHeight: { value: '1.5rem' },
      textTransform: { value: 'uppercase' },
      height: { value: '2rem' },
      borderRadius: { value: '0.25rem' },
      padding: { value: '0 0.5rem' },
    },
  },
};
